#
# ローカル開発環境
#
version: '3'
services:
      
  pm2:
    build: ./docker/pm2
    container_name: portal_pm2_container
    depends_on:
      - node
    volumes:
      - .:/pm2

  # watch用のコンテナ
  node:
    build: ./docker/node
    container_name: portal_node_container
    depends_on:
      - mysql
    links:
      - mysql:mysql
    tty: true
    volumes:
      - .:/pm2

  nginx:
    build: ./docker/nginx
    container_name: portal_nginx_container
    depends_on:
      - pm2
    ports:
      - 80:80
    volumes:
      - .:/pm2

  mysql:
    build: ./docker/mysql
    container_name: portal_mysql_container
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysql123
      MYSQL_DATABASE: portal
      MYSQL_USER: portal_user
      MYSQL_PASSWORD: portal_password
    volumes:
      - ./docker/mysql/test/data:/var/lib/mysql
      - ./docker/mysql/test/log:/var/log/mysql
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
