#
# ローカル開発環境（超シンプル構成）
#
version: '2'
services:

  node:
    build: ./docker/node
    container_name: portal_node_container
    hostname: node_server
    volumes:
      - "./:/var/www/sample"
    working_dir: /var/www/sample
    #command: [sh, -c, 'yarn install && cd src; npm run start:server']
    links:
      - mysql:mysql
      - memcached:memcached
    ports:
      - "3000:3000"

  node_api:
    build: ./docker/node
    container_name: portal_api_container
    hostname: node_api
    volumes:
      - "./src:/var/www/sample"
    working_dir: /var/www/sample
#    command: [sh, -c, 'npm install && npm run api:local']
    links:
      - mysql:mysql
      - memcached:memcached
    ports:
      - "3001:3001"

  nginx:
    build: ./docker/nginx
    container_name: portal_nginx_container
    ports:
      - "80:80"
    depends_on:
      - "node"
    volumes:
      - "./docker/nginx/conf.d:/etc/nginx/conf.d"
      - "./docker/nginx/logs:/var/log/nginx"
    links:
      - mysql
      - node
      - memcached:memcached

  mysql:
    build: ./docker/mysql
    container_name: portal_mysql_container
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: portal
      MYSQL_USER: portal_user
      MYSQL_PASSWORD: portal_password
    volumes:
      - ./docker/mysql/test/data:/var/lib/mysql
      - ./docker/mysql/test/log:/var/log/mysql
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: portal_phpmyadmin_contaier
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=portal_user
      - PMA_PASSWORD=portal_password
    links:
      - mysql
    ports:
      - 8080:80
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions

  memcached:
    container_name: portal_memcached_contaier
    image: memcached:1.4-alpine
